bedroomChoice = {
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  '6': 6,
  '7': 7,
  '9': 8,
  '9': 9,
  '10': 10,
}

priceChoices = {
  '3000000': '₦3000,000',
  '5000000': '₦5000,000',
  '700000': '₦700,000',
  '900000': '₦900,000',
  '11000000': '₦11M+',
}

stateChoices = {
  'FCT':'Abuja',
  'Abia':'Umuahia',
  'Adamawa':'Yola',
  'Akwa-Ibom':'Uyo',
  'Anambara':'Awka',
  'Buachi':'Bauchi',
  'Bayelsa':'Yenagoa',
  'Benue':'Makurdi',
  'Borno':'Maiduguri',
  'Cross-river':'Calabar',
  'Delta':'Asaba',
  'Ebonyi':'Abakali',
  'Edo':'Benin',
  'Ekiti':'Ado-ekiti',
  'Enugu':'Enugu',
  'Gombe':'Gombe',
  'Imo':'Owerri',
  'Jigawa':'Dutse',
  'Kaduna':'Kaduna',
  'Kano':'Kano',
  'Katsina':'Katsina',
  'Kebbi':'Birnin-kebbi',
  'Kogi':'Lokoja',
  'Kwara':'Ilorin',
  'Lagos':'Ikeja',
  'Nasarawa':'Lafia',
  'Niger':'Minna',
  'Ogun':'Abeokuta',
  'Ondo':'Akure',
  'Oshub':'Oshogbo',
  'Lagos':'Ibadan',
  'Plateau':'Jos',
  'Rivers':'Port-harcourt',
  'Sokoto':'Sokoto',
  'Taraba':'Jalingo',
  'Yobe':'Damaturu',
  'Zamfara':'Gusau',

}